### ISSUE TITLE
Cannot hear music

### ISSUE THREAD

**Issue by ember-island-engineer** [Banila48/Feels-on-Wheels#1]
Hi,

I love the project. However i can't hear the music being played. 

I'm on Chrome on macOS

**Comment by Banila48** [comment]
I tried on Opera and I have the same issue.

I managed to fix it by going to ```opera://settings/content/sound```

Then add the website to the "Allow" list. 

You can try doing it for chrome

```chrome://settings/content/sound```

**Comment by ember-island-engineer** [comment]
Nice thanks! Managed to get the fix as state above!

![image](https://user-images.githubusercontent.com/41948452/126648076-3abb4e4d-cc10-4918-8e94-95cb5e9f1912.png)
